#
# Copyright (C) 2021 Kian Cross
#

name: Java Spotbugs Annotations Uploader
author: Hiroshi Miura

description: >
  Uploads SpotBugs errors & warnings as GitHub Annotations and
  decorates the log file output. Compatible with forked PRs.

branding:
  icon: check-circle
  color: orange

runs:
  using: composite
  steps:
    - run: echo "::add-matcher::${{ github.action_path }}/problem-matcher.json"
      shell: bash
